### ISSUE TITLE
Fix eslint warnings in bin/www

### ISSUE THREAD

**Issue by rzgry** [rzgry/Express-REST-API-Template#7]
The app is currently using the `bin/www` that was automatically generated by [express generator](https://expressjs.com/en/starter/generator.html).

So it has a whole bunch of linter warnings when ran against the eslint configuration.

Right now eslint is disabled in this file by this line: 

https://github.com/rzgry/Express-REST-API-Template/blob/74cb4c490e1bdfc04d02a0d564c48d125953b298/src/bin/www#L3

Need to remove the `/* eslint disable */` line and fix the linter warnings in `bin/www`

Can lint just that file by running `npx eslint src/bin/www`

Should probably just use eslint-disable-line for any `no-console` errors, and fix all of the other errors (such as `no-var`).

Ex: 

```js
...
console.log(`Listening on ${bind}`); // eslint-disable-line no-console
...
```

**Comment by virenb** [comment]
I'd like to give this issue a try.

**Comment by rzgry** [comment]
Go for it 👍

**Comment by rwalter215** [comment]
I have a PR opened for this issue
