### ISSUE TITLE
Get travis to run eslint

### ISSUE THREAD

**Issue by rzgry** [rzgry/Express-REST-API-Template#8]
Current `.travis.yml` uses the default `script` which just runs `npm test`

https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#default-build-script

Would be nice to get travis to run both eslint (`npm run lint`) and the tests (`npm test`)

Example travis config with a linting step:  
https://gist.github.com/ronapelbaum/ef3c3459f01b002d0d719ca205401174

**Comment by MatheusRich** [comment]
I'm on it
